mathcore/book/urls.py
from django.urls import path, include
from . import views

app_name = 'book'
urlpatterns = [
    path('', views.bookprint, name='print'),
    path('booklist/', views.booklist)
]

mathcore/mathcore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('book.urls', 'book'),namespace='print')),
]

mathcore/book/models.py
from django.db import models

# Create your models here.
class BookList(models.Model):
    name = models.CharField(max_length=15)
    time = models.DateTimeField()
    answer = models.CharField(max_length=30)

    def __str__(self):
        return self.name

mathcore/book/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import BookList


# Create your views here.
def bookprint(request) :
    return render(request, 'book/printmenu.html')


def booklist(request) :
    booklistmem = BookList.objects.all()
    context = {'booklistmem' : booklistmem}
    return render(request, 'book/booklist.html', context)

mathcore/book/templates/book/booklist.html
{% extends "book/layout.html" %}
{% block title %}
책 목록
{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B>이름</B></td>
            <td><B>시간</B></td>
            <td><B>답안지</B></td>
        </tr>
        </thead>
        <tbody>
        {% for booklist in booklistmem %}
        <tr>
            <td>{{booklist.name}}</td>
            <td>{{booklist.time}}</td>
            <td>{{booklist.answer}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{%endblock%}
</html>

mathcore/book/templates/book/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{%block title%}{%endblock%}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="{% url 'book:print' %}"><B>Math-core 홈으로 돌아가기</B></a>
    </div>
</nav>
{%block content%}{%endblock%}
</body>
</html>

mathcore/book/templates/book/printmenu.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>메뉴</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <table class="table table-striped">
        <thead>
        <tr>
            <td><B><a href = "booklist/{{booklist.booklistmem}}">교재목록</a></B></td>
            <td><B><a href = "admin/"ADMIN>교재목록추가</a></B></td>
            <td><B><a href = "admin/"ADMIN>교재목록삭제</a></B></td>
        </tr>
        </thead>
    </table>
</div>
</body>
</html>